# Generated by Django 5.0.2 on 2024-03-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_desc',
            field=models.TextField(null=True),
        ),
    ]
