# Generated by Django 5.0.2 on 2024-03-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_alter_receipe_receipe_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_desc',
            field=models.TextField(),
        ),
    ]
