# Generated by Django 4.1.13 on 2024-03-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_employees_delete_receipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Employees_id',
            field=models.IntegerField(null=True),
        ),
    ]
