# Generated by Django 4.1.13 on 2024-03-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_alter_employees_employees_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=100)),
                ('receipe_desc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
