# Generated by Django 4.1.13 on 2024-03-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_employee_hours_worked_employee_overtime_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
